[package]
name = "password_generator"
version = "0.1.0"
edition = "2021"
authors = ["budigital"]
description = "A simple password generator with flags."

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
rand = "0.8.5"
